### ISSUE TITLE
Additional system dependencies aren't installed

### ISSUE THREAD

**Issue by DragoonAethis** [gcarq/inox-patchset#39]
Additional system dependencies (lines 9-22 in the current PKGBUILD) aren't appended to the depends list for some reason. Installing with pacaur, it happily skipped some deps, installed the package (inox-bin) and then Inox complained it couldn't find `libre2.so.0` (from `re2`) on start.

**Comment by gcarq** [comment]
I've added the dependencies hardcoded, should be fixed

**Comment by DragoonAethis** [comment]
You forgot to bump the pkgrel to 2 :P But the new PKGBUILD works fine, thanks.

**Comment by gcarq** [comment]
Dang! :D
